# Generated by Django 3.2.7 on 2024-06-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlySignOff',
        ),
    ]
