# Generated by Django 3.2.7 on 2024-06-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0003_monthlysignoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.month')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'month')},
            },
        ),
    ]
