# Generated by Django 3.2.7 on 2024-06-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0005_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
