# Generated by Django 3.2.7 on 2024-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0006_maintenancerequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
