# Generated by Django 3.2.7 on 2024-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0007_payment_mpesa_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='avatar',
            field=models.ImageField(default='media/avatar.svg', upload_to='media'),
        ),
    ]
