# Generated by Django 3.2.7 on 2024-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0008_alter_tenant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin'), ('developer', 'Developer')], max_length=20),
        ),
    ]
