# Generated by Django 3.2.7 on 2024-07-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0010_qnaresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10),
        ),
    ]
